
name: Build image

on:
  push:
    branches: [ Development ]
  pull_request:
    branches: [ Development ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u "${{ github.actor }}" --password-stdin
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push development docker image
        run: |
          docker buildx build \
            --tag ghcr.io/girdauskas/dotnetruntime:development \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --push .
